# Generated by Django 4.2.7 on 2023-11-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_staf',
            new_name='is_staff',
        ),
    ]
